# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'JarvisUi.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1366, 720)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        
        self.bg_1 = QtWidgets.QLabel(self.centralwidget)
        self.bg_1.setGeometry(QtCore.QRect(-470, -150, 1911, 1071))
        self.bg_1.setText("")
        self.bg_1.setPixmap(QtGui.QPixmap("./G.U.I Material/B.G/Black_Template.jpg"))
        self.bg_1.setScaledContents(True)
        self.bg_1.setObjectName("bg_1")
        
        
        self.bg_2 = QtWidgets.QLabel(self.centralwidget)
        self.bg_2.setGeometry(QtCore.QRect(10, 20, 421, 361))
        self.bg_2.setStyleSheet("background-color: rgb(0, 255, 255);\n"
"background-color: rgb(16, 178, 214);")
        self.bg_2.setText("")
        self.bg_2.setObjectName("bg_2")
        
        self.Gif_1 = QtWidgets.QLabel(self.centralwidget)
        self.Gif_1.setGeometry(QtCore.QRect(20, 30, 401, 341))
        self.Gif_1.setText("")
        self.Gif_1.setPixmap(QtGui.QPixmap("./G.U.I Material/B.G/Iron_Template_1.gif"))
        self.Gif_1.setScaledContents(True)
        self.Gif_1.setObjectName("Gif_1")


        self.bg_3 = QtWidgets.QLabel(self.centralwidget)
        self.bg_3.setGeometry(QtCore.QRect(440, 20, 391, 361))
        self.bg_3.setStyleSheet("background-color: rgb(0, 255, 255);\n"
"background-color: rgb(16, 178, 214);")
        self.bg_3.setText("")
        self.bg_3.setObjectName("bg_3")
        
        
        self.Gif_2 = QtWidgets.QLabel(self.centralwidget)
        self.Gif_2.setGeometry(QtCore.QRect(450, 30, 371, 341))
        self.Gif_2.setText("")
        self.Gif_2.setPixmap(QtGui.QPixmap("./G.U.I Material/ExtraGui/live.gif"))
        self.Gif_2.setScaledContents(True)
        self.Gif_2.setObjectName("Gif_2")
        
        
        self.Gif_3 = QtWidgets.QLabel(self.centralwidget)
        self.Gif_3.setGeometry(QtCore.QRect(20, 340, 481, 351))
        self.Gif_3.setText("")
        self.Gif_3.setPixmap(QtGui.QPixmap("./G.U.I Material/VoiceReg/Siri_1.gif"))
        self.Gif_3.setScaledContents(True)
        self.Gif_3.setObjectName("Gif_3")
        
        
        self.bg_4 = QtWidgets.QLabel(self.centralwidget)
        self.bg_4.setGeometry(QtCore.QRect(840, 20, 391, 281))
        self.bg_4.setStyleSheet("background-color: rgb(0, 255, 255);\n"
"background-color: rgb(16, 178, 214);")
        self.bg_4.setText("")
        self.bg_4.setObjectName("bg_4")
        
        
        self.Gif_4 = QtWidgets.QLabel(self.centralwidget)
        self.Gif_4.setGeometry(QtCore.QRect(850, 30, 371, 261))
        self.Gif_4.setText("")
        self.Gif_4.setPixmap(QtGui.QPixmap("./G.U.I Material/ExtraGui/Earth.gif"))
        self.Gif_4.setScaledContents(True)
        self.Gif_4.setObjectName("Gif_4")
        
        
        self.Text_Time = QtWidgets.QTextBrowser(self.centralwidget)
        self.Text_Time.setGeometry(QtCore.QRect(950, 500, 351, 71))
        self.Text_Time.setStyleSheet("\n"
"background-color: Transparent;")
        self.Text_Time.setObjectName("Text_Time")
        
        
        self.bg_5 = QtWidgets.QLabel(self.centralwidget)
        self.bg_5.setGeometry(QtCore.QRect(990, 590, 341, 91))
        self.bg_5.setText("")
        self.bg_5.setPixmap(QtGui.QPixmap("./G.U.I Material/B.G/gyhf.jpg"))
        self.bg_5.setScaledContents(True)
        self.bg_5.setObjectName("bg_5")
        
        
        self.bg_6 = QtWidgets.QLabel(self.centralwidget)
        self.bg_6.setGeometry(QtCore.QRect(870, 310, 381, 121))
        self.bg_6.setStyleSheet("background-color: rgb(0, 255, 255);\n"
"background-color: rgb(16, 178, 214);")
        self.bg_6.setText("")
        self.bg_6.setObjectName("bg_6")
        
        
        self.pushButton_start = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_start.setGeometry(QtCore.QRect(880, 320, 341, 41))
        self.pushButton_start.setStyleSheet("background-color:rgb(0,0,0);\n"
"color: rgb(0,255,255);\n"
"font: 24pt \"Nirmala UI\";")
        self.pushButton_start.setObjectName("pushButton_start")
        self.pushButton_exit = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_exit.setGeometry(QtCore.QRect(880, 380, 341, 41))
        self.pushButton_exit.setStyleSheet("background-color:rgb(0,0,0);\n"
"color: rgb(0,255,255);\n"
"font: 24pt \"Nirmala UI\";")
        self.pushButton_exit.setObjectName("pushButton_exit")
        self.pushButton_youtube = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_youtube.setGeometry(QtCore.QRect(360, 400, 151, 61))
        self.pushButton_youtube.setStyleSheet("font: 18pt \"MS Shell Dlg 2\";\n"
"background-color: rgb(85,255,255);")
        self.pushButton_youtube.setObjectName("pushButton_youtube")
        self.pushButton_chrome = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_chrome.setGeometry(QtCore.QRect(530, 400, 151, 61))
        self.pushButton_chrome.setStyleSheet("font: 18pt \"MS Shell Dlg 2\";\n"
"background-color: rgb(85,255,255);")
        self.pushButton_chrome.setObjectName("pushButton_chrome")
        self.pushButton_whatsapp = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_whatsapp.setGeometry(QtCore.QRect(700, 400, 151, 61))
        self.pushButton_whatsapp.setStyleSheet("font: 18pt \"MS Shell Dlg 2\";\n"
"background-color: rgb(85,255,255);")
        self.pushButton_whatsapp.setObjectName("pushButton_whatsapp")
        
        self.bg_1.raise_()
        self.Gif_3.raise_()
        self.bg_2.raise_()
        self.Gif_1.raise_()
        self.bg_3.raise_()
        self.Gif_2.raise_()
        self.bg_4.raise_()
        self.Gif_4.raise_()
        self.Text_Time.raise_()
        self.bg_5.raise_()
        self.bg_6.raise_()
        self.pushButton_start.raise_()
        self.pushButton_exit.raise_()
        self.pushButton_youtube.raise_()
        self.pushButton_chrome.raise_()
        self.pushButton_whatsapp.raise_()
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.pushButton_start.setText(_translate("MainWindow", "Start"))
        self.pushButton_exit.setText(_translate("MainWindow", "Exit"))
        self.pushButton_youtube.setText(_translate("MainWindow", "Youtube"))
        self.pushButton_chrome.setText(_translate("MainWindow", "Chrome"))
        self.pushButton_whatsapp.setText(_translate("MainWindow", "Whatsapp"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
